server:
  port: 8080
  sessionTimeout: 30
  contextPath: /wxbot
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8


############ jdbc connetions #############
spring.datasource:
  url: jdbc:mysql://localhost:3306/wxbot?useUnicode=true&amp;characterEncoding=utf8
  username: root
  password: 12345678
  driver-class-name: com.mysql.jdbc.Driver


#spring.mvc.view:
#  prefix: /views/
#  suffix: .jsp

#LOG
logging.level.root: info

spring.devtools.restart.enabled: true

spring.beetl:
  root: classpath:/templates/
  prefix: /templates/
  suffix: .html
  order: 0
  config: classpath:beetl.properties